apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus-pushgateway
  namespace: monitoring
spec:
#  clusterIP: 10.43.11.101
  ports:
  - name: http
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: prometheus
    component: pushgateway
    release: prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
