apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-redis-exporter
    chart: prometheus-redis-exporter-3.4.1
    heritage: Tiller
    io.cattle.field/appId: prod-minder-redis2-exporter
    release: prod-minder-redis2-exporter
  name: prod-minder-redis2-exporter-prometheus-redis-exporter
  namespace: monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus-redis-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prometheus-redis-exporter
    spec:
      containers:
      - env:
        - name: REDIS_ADDR
          value: prod-minder-redis.internal.corescientific.com:32677
        image: oliver006/redis_exporter:v1.3.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: exporter-port
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: prometheus-redis-exporter
        ports:
        - containerPort: 9121
          name: exporter-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: exporter-port
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
